apiVersion: v1
kind: Namespace
metadata:
  name: spark-runner
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-runner-service-account
  namespace: spark-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-runner-role
  namespace: spark-runner
subjects:
  - kind: ServiceAccount
    name: spark-runner-service-account
    namespace: spark-runner
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io