apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark-runner-service-account
  namespace: airflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: spark-runner-role
  namespace: airflow
subjects:
  - kind: ServiceAccount
    name: spark-runner-service-account
    namespace: airflow
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: airflow-default-role
  namespace: airflow
subjects:
  - kind: ServiceAccount
    name: default
    namespace: airflow
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io